#----------------------------------------------------------------------------------------------------------------------------
# Purpose: Define the infrastructure stack (DB, Redis, MinIO)
#----------------------------------------------------------------------------------------------------------------------------

name: smartats

services:
  # 1. The Postgres Database
  db:
    image: postgres:15-alpine
    restart: always
    environment:
      POSTGRES_USER: resume_user
      POSTGRES_PASSWORD: resume_pass
      POSTGRES_DB: resume_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    
  # 2. The Redis Message Broker
  redis:
    image: redis:7-alpine
    restart: always
    ports:
      - "6379:6379"
  
  # 3. The Object Storage MinIO (S3-Compatible Storage)
  minio:
    image: minio/minio
    restart: always
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    ports:
      - "9000:9000" #API Port
      - "9001:9001" # Console Port
    volumes:
      - minio_data:/data

  # 4. The API Server ( FastAPI) - We explicitly definte this now 
  # PReviously we ran this locally , but to network correctly with the worker 
  # inside Docker, it helps to define the dstructure.
  # For thischapter, we will stick to running the worker defnition here
  # But might execute locally for ease of debugging

  # 5. The background Worker (Celery)
  worker:
    build: .
    command: celery -A app.worker.celery_app worker --loglevel=info
    volumes:
      - .:/app
    environment:
      # Override localhost with container names
      CELERY_BROKER_URL: redis://redis:6379/0
      CELERY_RESULT_BACKEND: redis://redis:6379/0
      DATABASE_URL: postgresql://resume_user:resume_pass@db:5432/resume_db
      MINIO_ENDPOINT: http://minio:9000
      # AI COnfigs
      AI_MODE: gemini
      GEMINI_API_KEY: ${GEMINI_API_KEY}
    depends_on:
    - redis
    - db

  
volumes:
  postgres_data:
  minio_data:
