# -----------------------------------------------------------------------------------------------------------------------------------------------
# Purpose: Nginx Reverse Proxy Configuration
# -----------------------------------------------------------------------------------------------------------------------------------------------

events {}

http {
    upstream fastapi_app {
        # 'web' matches the service name in docker-compose
        server web:8000;
    }

    server {
        listen 80;

        location / {
            proxy_pass http://fastapi_app;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;

            # Allow large file uploads (Resume PDFs)
            client_max_body_size 10M;
        }
    }
}